name: Build, Test, Lint for Pull Requests

on: [pull_request]

jobs:
  build:
    strategy:
      matrix:
        node-version: [14.x, 16.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: |
          npm ci
          npm run bs

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test

      - name: Lint
        run: npm run lint
